### PR TITLE
Configs/env vars: s/OPT_/ABC_.

### PR DESCRIPTION
**Pull request by webbhorn**
Previously we had lots of environment variables prefixed with OPT
as a holdover from the Optics fork. This PR tries to migrate them to
Abacus-specific prefix of ABC, which is something we'd said we'd like
to do prior to handing operational responsibility for running agents to
any third parties, since there will be some inherent resistance in
persuading a group like that to rename all configuration variables.

If desired, I'm happy to hold on this since we have so much in-flight
at the moment, just sending out for initial comment. On the other hand,
maybe it's better to catch and fix any issues as soon as we can.

This was a fairly blind find-and-replace for OPT_ and OPT strings within
the repo. I'm less familiar with the agent deploy/release process so am
leaning to some extent on @tkporter / @nambrot to comment on whether
I've managed to miss any of the critical config-generating pieces of code.

### CODE REVIEW

**Review by nambrot — APPROVED** [review]
lgtm, though I would defer to @tkporter whether external-secrets can automatically update it's secrets it manages. I believe yes

**Comment by webbhorn** [comment]
Thanks, I'll wait for Trevor.

**Comment by webbhorn** [comment]
Resolved merge conflict (new whitelist-related env var for relayer in run-locally.sh), verified still works by running run-locally.sh and watching logs.

**Review by tkporter — APPROVED** [review]
lgtm! I just deployed using a new image so we don't get into a situation where we accidentally deploy using an image that expects OPT_* but ABC_* is supplied.

**Pull request merged**
